<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{296c9099-8b07-4824-9c8d-85d794132ef3}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	MachineControll : MachineControlMode ; 
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[MachineControll();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>